### ISSUE TITLE
API Wrapper occasionally hanging while communicating with Blizzard

### ISSUE THREAD

**Issue by tehmufifnman** [jyggen/bnet#23]
I noticed some of my scripts appeared to be locked up, so I set about investigating.

My steps:
Retrieved the processId of my script
Then ran "strace -p <pid>" which showed it stuck on "fd 10"
"lsof -p <pid>" shows all fds for my process, and 10 is a TCP connection from my server to an IP address owned by Blizzard Paris (which I am assuming is me downloading auction data from an EU server).

The API wrapper function call that is hanging is:
`$this->apiClient->auctions()->download($auctionIndex);`

This is called with an appropriately verified $auctionIndex, since I compare it to a stored index in my DB to check if new data is available from Blizzard.

This happens extremely rarely, but when it does it manages to hard-lock my script for some reason.

Any ideas?

Thanks and keep up the amazing work!

**Comment by morloderex** [comment]
This may not be our fault i might be blizzard issue. 

But i need to investigate this further. 

Which i may be doing later tonight.

**Comment by jyggen** [comment]
Sounds like Blizzard's servers are wonky. I've seen other weird things happen in the past, especially with the auction house API. 

The library we use for HTTP requests, [Guzzle](https://github.com/guzzle/guzzle), will wait indefinitely for a request by default - so if Blizzard never respond then you'll script will never finish either. 

You could provide your own Guzzle client with a timeout set through `setClient()` and see if it solves your issue.

**Comment by tehmufifnman** [comment]
Would any options I setup in setClient() not be overwritten when the
default options are set on the client in makeRequest()?

Maybe related, maybe something completely different, but I just noticed 2
cURL errors:
cURL error 6: Could not resolve host: us.api.battle.net (see
http://curl.haxx.se/libcurl/c/libcurl-errors.html)
cURL error 18: transfer closed with outstanding read data remaining (see
http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by jyggen** [comment]
The options you send to the constructor of Guzzle acts as defaults, so as long _we_ don't override them they _should_ be kept, and we don't provide a timeout value.
