### ISSUE TITLE
Bump minimum PHP version to 7.0

### ISSUE THREAD

**Issue by jyggen** [jyggen/bnet#27]
Thoughts? It would allow us to use all the lovely new features. The minimum version should _at least_ be bumped to 5.6 since 5.5 goes EOL in 4 days.

**Comment by morloderex** [comment]
I'm okay with _atleast_ it being bumped to 5.6, but which new features do you have in mind for the package, it's pretty much covered all around isn't it?

**Comment by jyggen** [comment]
PHP 7 features such as strict mode, scalar type hinting, return types etc. But they're obviously just "nice to have" :P

**Comment by morloderex** [comment]
I'm not that sure about forcing the use of 7.0 :P 

Maybe we should keep it at 5.6 and then wait little but more..

**Comment by jyggen** [comment]
Minimum version bumped to PHP 7.1 in mater.
